### ISSUE TITLE
Test_ErrorComputation

### ISSUE THREAD

**Issue by agarllo** [BAMresearch/PGDrome#7]
Compute error in the tests

**Comment by agarllo** [comment]
I created this issue to update the tests. It was implemented a class to compute the error (norm L2) in model.py. This new application has already been applied in test_elastic.py and test_Elastic2D_4variables.py. You can check these tests to see how should be implemented. I think test_Elastic2D_4variables.py is more similar to your test because is a FEM results are used to compute the error.

If you have any problem with the implementation or any improvement, let me know.

**Comment by DoStrobl** [comment]
I've updated the _test_thermo to the new Error computation method and deleted the .dat file which is not used anymore. So far it is working, but i have two things to point out checking the code:

1. Using the "fixed_var" input in "PGDErrorComputation" does not work for me. In line 1369 of model.py PGDrome tries to compute a vector of an array which does not work.
2. @aradermacher please confirm if this is true or a false thought:
In line 1397 of model.py is the evaluation of the PGD_model. Later on, if "fixed_var" is not set, the error is computed over the whole fixed_dim domain. This may become a problem, since the PGD_solution does not take non-homogeneous boundary conditions in the fixed_dim into account, which has to be set manually after the evaluation. Thus this manual set up phase of the non-homo BC needs to be added after the evaluation.

**Comment by aradermacher** [comment]
Hi,

I also updated the test_solver_problem.py with the new error computation feature. 

regarding Dominics comments:
1) Aratz can you check that. In my vase it also didn't worked. I have a 2D mesh and the fixed_var is a 2D point (x,y) and I get an error in line 1366. See my test file line 471ff (comment part)
2) In my opinion non-homogeneous boundary condition should be saved in the pgd model class and then automatically be added in the evaluation function. In that way it should work with the Errorcompoutaion class.


additional remarks from my side:
- the fixed_dim variable is a scalar not an array! Otherwise the evaluation function of the pgd model class is not working.
- please add a little bit more about the required structure of the FOM_model -> call function has to give a fenics funtion or ndarray for the required space ...
- in test_elastic the last error computation is not right --> error_uPGD is not used and also fun_FOM2!! If I change this than it will not work!!

**Comment by agarllo** [comment]
Dominic's remarks:
- The problem in your test was that it wasn't defined the solution with the fixed parameter in "Reference_solution". I have modified your test and now I am running to check if it works well. Running in debugging goes really slow and I couldn't check it yet. If we copy from "test_elastic2D_4varibles" lines 344-350, 415-434 or from "test_colver_problem" lines 475-480, 398-406, it should we working. I am gonna leave running, we will see if it works tomorrow morning.

Annika's remarks:
- Checked and solved the error (Commented part)
- fixed_dim is scalar.
- The implemented code can work with ndarray and fenics function. I have added a comment in FOM_solution to clarify the type of the variable.
- test_elastic: Corrected

**Comment by DoStrobl** [comment]
Even though the test is running i have a feeling that something isn't right. 

In generel taking more then 1 specific point doesn't change the error very much.

In test_elastic the error at each point is basically the same (this might be true).

In test_thermo taking the whole x-space via
`tmp=[]`
`for coord in meshes[0].coordinates()[:]: tmp.append(coord[0])`
`x_test = tmp  # x (fixed variable)`
gives something different then not specifing any x (default is error over the whole x-space).
Additionally in test_thermo the Max. error is always the same as the Mean error, which feels wrong.

**Comment by aradermacher** [comment]
I agree with Dominic, that it is somehow weird that in test_elastic all errors are the same. I also didn't agree with the error_uPGD in line 235: In my opinion the data_test should only include amplitude & elastic modulus  and fixed_var should be 0.5 and the FOM_model=fun_FOM2!

**Comment by agarllo** [comment]
The max and mean error are the same when you compute the error in one point, because the error is just computed in one point. If you add more points or cases,  the max. and mean error will be different.
The test_elastic is linear problem (linear elastic and 1D), so the error must be almost the same if you consider the whole domain or one point. However, if you plot the error distribution in the whole domain in the other elastic tests, which are in 2D and plane strain conditions, you will see that there are greater differences in the values of the error between the points.

**Comment by agarllo** [comment]
I will check how it is defined the data_test

**Comment by DoStrobl** [comment]
> The max and mean error are the same when you compute the error in one point, because the error is just computed in one point. If you add more points or cases, the max. and mean error will be different. The test_elastic is linear problem (linear elastic and 1D), so the error must be almost the same if you consider the whole domain or one point. However, if you plot the error distribution in the whole domain in the other elastic tests, which are in 2D and plane strain conditions, you will see that there are greater differences in the values of the error between the points.

If i add more points in test_thermo, e.g. x_test = [0.01,0.05,0.09], the max and mean errors are the same. This is also true if i take the whole x-space as descripted above.

**Comment by agarllo** [comment]
I have updated test_elastic. I forgot uploading the new version.
I will check it Dominic.

**Comment by aradermacher** [comment]
Thanks
I would suggest to delete the second error computation in test_elastic. I would say the first and the last one shows all possible options already. 
The error limit <1e-3 is much to large here. I suggest to use something near the computed values (e.g. 1e-5 for the first one and 1e-7 for the last one ), so that if we change something, we really saw that by failing tests!!

**Comment by agarllo** [comment]
Dominic, it computes one error because it is comparing the results in every point you indicated ([0.01, 0.05, 0.09]) instead of the whole domain (every nodes). But as it is only defined one case (data_test), it is only computed one error. If you introduce more cases (data_test = [[1., 0.8], [5., 0.85]]), you will get the error for each case and there will be differences between the mean and max. Would you like to have the option to know the error in each geometrical point?

**Comment by agarllo** [comment]
Removed 2nd error computation and updated the error limits.
